version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pizza_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
        networks:
            - pizza

    webserver:
        image: nginx:alpine
        container_name: pizza_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pizza

    db:
        image: mysql:8.0
        container_name: pizza_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 123qwe
            MYSQL_DATABASE: pizza
            MYSQL_USER: user
            MYSQL_PASSWORD: 123qwe
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - pizza

networks:
    pizza:

volumes:
    dbdata:
